name: Deploy latest image on server

on:
    workflow_run:
        workflows: ["CI latest image"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy with use of SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_ADDRESS }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  port: 22
                  script: |
                      docker compose -f compose-latest.yaml down
                      docker pull godot911/tbo-projekt:latest
                      docker compose -f compose-latest.yaml up -d
